name: Build Main

on:
  push:
    tags:
      - "*main*"

concurrency:
  group: limit-one
  cancel-in-progress: false

jobs:
  setup_runner:
    name: Setup Runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Start Instance
        run: ./scripts/start_vm.sh
        env:
          TOKEN: ${{ secrets.COREWEAVE_TOKEN }}
          NAMESPACE: ${{ secrets.COREWEAVE_NAMESPACE }}

  build_and_publish_cog:
    name: Build and Publish Cog
    runs-on: self-hosted
    needs: setup_runner
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: main

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Prune Docker
        if: success()
        shell: bash
        run: docker system prune -f

      - name: Install custom cog
        if: success()
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: stablecog/cog
          extension-matching: disable
          rename-to: cog
          chmod: 0755

      - name: Download Weights
        if: success()
        shell: bash
        run: chmod u+x models/download; cog run models/download ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Build & Tag
        if: success()
        shell: bash
        run: cog build -t stablecog/sc-cog:latest

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        if: success()
        shell: bash
        run: docker push stablecog/sc-cog:latest
      
      - name: Login to GHCR
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        if: success()
        shell: bash
        run: docker tag stablecog/sc-cog:latest ghcr.io/stablecog/sc-cog:latest; docker push ghcr.io/stablecog/sc-cog:latest
        
  destroy_runner:
    name: Stop instance
    runs-on: ubuntu-latest
    if: always()
    needs: build_and_publish_cog

    steps:
      - uses: actions/checkout@master

      - name: Stop VM
        run: ./scripts/stop_vm.sh
        env:
          TOKEN: ${{ secrets.COREWEAVE_TOKEN }}
          NAMESPACE: ${{ secrets.COREWEAVE_NAMESPACE }}
