name: CI

on:
  push:
    branches: [main]

jobs:
  setup_runner:
    name: Deploy GH Runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup
        uses: bbedward/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes/setup.yaml

  build_and_publish_cog:
    name: Build and Publish Cog
    runs-on: self-hosted
    needs: setup_runner
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@master

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Download Weights
        if: success()
        shell: bash
        run: chmod u+x models/download; cog run models/download ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Build & Tag
        if: success()
        shell: bash
        run: cog build -t stb.sh/sc:latest

      - name: Login to registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: stb.sh
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to registry
        if: success()
        shell: bash
        run: docker push stb.sh/sc:latest

  destroy_runner:
    name: Destroy GH Runner
    runs-on: ubuntu-latest
    if: always()
    needs: setup_runner
    steps:
      - name: Destroy
        uses: bbedward/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete interferenceservices github-runner
